<?php


namespace classes;
include("FormControl.php");
class DietFormControl extends FormControl
{
    public function __construct($title, $body, $img){

    parent::__construct($title, $body, $img);

    }



public function inputsValidation()
{
    return parent::inputsValidation(); // TODO: Change the autogenerated stub
}

public function formValidation()
{

    $send = true;
    if($this->inputsValidation() == false){
        $send = false;
        return $this->errorForm['inputs'];
    }if($send == true){
    $this->addDietToDataBase("$this->title", "$this->body", $this->img);

}
    return $send;
}

}